### ISSUE TITLE
[Suggestion] Cursor position preselect at frequency entry...

### ISSUE THREAD

**Issue by dl9sec** [davecrump/ryde-build#38]
Hi Dave,

the cursor at the frequency entry always starts at the most left position.
E.g. for QO-100 I always have to change the last 4 digits of the frequency, the first four digits are always the same.
For a quick tune it would be helpful to preset the cursor start position. This maybe could be done via the config.yaml.
So when the cursor preset is set to 5, the cursor is set to the fifth digit: "1049**3**250" (cursor position is bold here).

Would be great if you could put that into your backlog.

Thank you in advance.

73, Thorsten

**Comment by davecrump** [comment]
I think now that external Quick Tune is working, the small advantage gained by this proposed change does not justify making the user interface inconsistent in its behaviour.
Dave
