### ISSUE TITLE
[Suggestion] Show current IP in the OSD menu

### ISSUE THREAD

**Issue by dl9sec** [davecrump/ryde-build#45]
Hi Dave,

it would be very helpful (especially if the Ryde RPi works with DHCP) to be able to easily get the current IP of the RPi.
This could be displayed e.g. at the bottom of the OSD menu or maybe in a special "Info" menu point...

73, Thorsten

**Comment by davecrump** [comment]
Hi Thorsten

Excellent idea, but this request is already covered in the RydePlayer Issues List.  [https://github.com/eclispe/rydeplayer/issues/27](https://github.com/eclispe/rydeplayer/issues/27)
Dave
